#!/bin/bash

DIR=`pwd`/`dirname $0`;
TEMP_DIR=$DIR/temp

rm -rf $TEMP_DIR/*

rm $DIR/../composer.lock
cd $DIR/..
composer install --no-interaction --prefer-source

$DIR/../vendor/bin/tester -p php $DIR -s -j 5 --colors 1 -c $DIR/config/php-unix.ini