#!/bin/bash

DIR=`pwd`/`dirname $0`;
TEMP_DIR=$DIR/temp

rm -rf $TEMP_DIR/*

rm $DIR/../composer.lock
cd $DIR/..
composer install --no-interaction --prefer-source

INTERPRET='';
if [ "$1" == "" ]; then
	INTERPRET="php"
else
	INTERPRET=$@
fi

$DIR/../vendor/bin/tester -s -j 5 --colors 1 -c $DIR/config/php-unix.ini -p $INTERPRET $DIR/src